### ISSUE TITLE
Implement MongoDB streaming - eg. Mercury servers should listen for changes made in database collection

### ISSUE THREAD

**Issue by sinbad-io** [nuntiodev/mercury#6]
When a user sends a message to a server, that server inserts a document in a database. 
All other Mercury servers should listen for changes on the Mongo database and check if a user is connected and stream that message to the users device.

Check this: https://ksingh7.medium.com/mongodb-change-streams-implementation-in-golang-21b52709d138

**Comment by JesperSteensgaard** [comment]
Test
