### ISSUE TITLE
Implement get 10 most recent chat conversations

### ISSUE THREAD

**Issue by sinbad-io** [nuntiodev/mercury#7]

**Comment by JesperSteensgaard** [comment]
ListConversations(user, 0, N) retrieves the N most recent conversations, sorted by last message sent in conversation.
Each conversation has a field LastMessage.

It is non-obvious how to retrieve the N most recent messages efficiently:
A user might be added to a conversation after the message was sent or removed from a conversation.

**Comment by sinbad-io** [comment]
Is this only a problem if a user is removed or added to a conversation? 
If so, let's checkout what Facebook does and do the same...

**Comment by JesperSteensgaard** [comment]
I think Facebook does not provide a way to get most recent chat messages. Is this feature necessary? If a user really needs such a list, he could retrieve the most recent conversations, and the most recent messages in each of these conversations.

**Comment by sinbad-io** [comment]
Sorry, this title is wrong - it should have been implement 10 most recent converstations... I'll update it right now
